/**
 * Per-user event Hypercore operations.
 *
 * Each user's earn/spend events are stored in their own Hypercore inside
 * the shared Corestore at ~/.ash/corestore/. The admin's MintEvents are
 * stored in the admin's own Hypercore (named by ADMIN_PUBKEY) and read by
 * all peers during balance calculation.
 */

import { getCorestore } from "./store.ts";
import { getPeerLedgerKey } from "./peer_keys.ts";
import type { Event, SpendCheckpointEvent, EarnCheckpointEvent } from "../../shared/events.ts";
import { eventWithoutSignature, checkpointPayload } from "../../shared/events.ts";
import { ADMIN_PUBKEY, ADMIN_LEDGER_KEY } from "../../shared/constants.ts";
import { verifyEd25519, rawHexToPublicKey } from "../crypto/ed25519.ts";
import { canonicalStringify } from "../../shared/canonical.ts";
import { withTimeout } from "../util/async.ts";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function getUserCore(ownerPubkeyHex: string): Promise<any> {
  const store = await getCorestore();
  const ns = store.namespace("ash-events");
  const core = ns.get({ name: ownerPubkeyHex, valueEncoding: "utf-8" });
  await core.ready();
  return core;
}

/** Returns the hex key of the given owner's event Hypercore. */
export async function getCoreKey(ownerPubkeyHex: string): Promise<string> {
  const core = await getUserCore(ownerPubkeyHex);
  return (core.key as Buffer).toString("hex");
}

/** Returns how many events are in the owner's Hypercore (= next nonce). */
export async function getEventCount(ownerPubkeyHex: string): Promise<number> {
  const core = await getUserCore(ownerPubkeyHex);
  return core.length as number;
}

/** Appends a signed event to the owner's Hypercore. */
export async function appendEvent(ownerPubkeyHex: string, event: Event): Promise<void> {
  const core = await getUserCore(ownerPubkeyHex);
  await core.append(JSON.stringify(event));
}

/**
 * Replays earn/spend events from a core to compute base balance.
 *
 * Replay-time invariants (forgery defense):
 *   1. SpendEvent must be signed by the log owner. Prevents third-party
 *      tampering during Hypercore replication.
 *   2. EarnEvent must be signed by `counterparty_pubkey`. Mirrors the
 *      wire-level check at serve.ts earn-cosign validation.
 *   3. EarnEvent must correspond to a matching SpendEvent on the
 *      counterparty's own log. Closes the "fake counterparty keypair"
 *      forgery: an attacker who mints a throwaway keypair Y and self-signs
 *      an earn in their own log cannot produce a matching spend in Y's
 *      core (Y is empty or never replicated), so the earn is dropped.
 *   4. Running balance stays ≥ 0. A spend that would drive balance negative
 *      is skipped rather than applied; defense-in-depth against a
 *      compromised owner signing an over-spend.
 *
 * Any event that fails these checks is treated as malformed and skipped.
 */
// `startingBalance` is the pre-applied admin-mint total for this owner;
// injecting it here lets the spend underflow guard compare against the
// real available balance instead of 0 (which would drop every spend that
// lands before the first earn — see the /status vs /history mismatch bug).
// `startIndex` allows partial replay from a known-good checkpoint position,
// so post-checkpoint legacy events (e.g. mine EarnEvents) are still counted.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function replayBalance(core: any, ownerPubkeyHex: string, startingBalance = 0, startIndex = 0, verifiedMintedPubkeys?: Set<string> | null, waitForBlocks = false, counterpartyKeyOverrides?: Record<string, string>): Promise<number> {
  let balance = startingBalance;
  const len: number = core.length;
  let ownerPubKey: ReturnType<typeof rawHexToPublicKey> | null = null;
  try {
    ownerPubKey = rawHexToPublicKey(ownerPubkeyHex);
  } catch {
    return 0;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const coreCache = new Map<string, any>();
  // Dedupe earns by task_id so a single spend cannot fund multiple earns.
  // (Each task_id is generated by the requester per task; a real workflow
  // produces exactly one earn per task_id. A duplicate earn for the same
  // task_id is either a buggy retry or a deliberate inflation attack.)
  const seenEarnTaskIds = new Set<string>();
  // Same protection for spend events: Hypercore append is non-idempotent,
  // so a sign-then-retry race could land two identical SpendEvents in
  // the log. Without this dedupe the user would be double-debited.
  const seenSpendNonces = new Set<number>();
  for (let i = startIndex; i < len; i++) {
    try {
      const raw = await core.get(i) as string;
      const event = JSON.parse(raw) as Event;
      // Only `spend` and `earn` move balance. Other event types
      // (`signup`, `mint`, `policy_update`, `task_*`) are recorded for
      // audit and replay-time signature checks but contribute zero to
      // the running balance — by design. Adding a new balance-affecting
      // event type means adding a case here.
      if (event.type === "spend") {
        if (seenSpendNonces.has(event.nonce)) continue;
        if (event.amount < 0) continue; // negative amount would inflate balance
        const ok = verifyEd25519(
          canonicalStringify(eventWithoutSignature(event)),
          event.signature,
          ownerPubKey,
        );
        if (!ok) continue;
        seenSpendNonces.add(event.nonce);
        // Negative balance is allowed: it exposes fraudulent spends instead
        // of silently masking them (a skipped spend still lets the
        // counterparty claim the earn via cross-ref — so skipping creates an
        // asymmetric ledger). Live `balance > 0` checks in serve.ts still
        // gate task acceptance, so a negative owner can't keep spending.
        balance -= event.amount;
      } else if (event.type === "earn") {
        if (seenEarnTaskIds.has(event.task_id)) continue;
        const accepted = await verifyEarnCrossRef(event, ownerPubkeyHex, coreCache, verifiedMintedPubkeys, waitForBlocks, counterpartyKeyOverrides);
        if (!accepted) continue;
        seenEarnTaskIds.add(event.task_id);
        balance += event.amount;
      }
    } catch {
      // skip malformed entries
    }
  }
  return balance;
}

/**
 * Validates a single EarnEvent observed in `ownerPubkeyHex`'s log:
 *   - signature verifies against `counterparty_pubkey`
 *   - counterparty's log contains a matching SpendEvent (same task_id,
 *     same amount ≥ earn.amount when fees apply in future, counterparty ===
 *     owner, and signed by counterparty)
 *
 * Returns true if the earn should be credited.
 */
async function verifyEarnCrossRef(
  earn: Extract<Event, { type: "earn" }>,
  ownerPubkeyHex: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  coreCache: Map<string, any>,
  verifiedMintedPubkeys?: Set<string> | null,
  waitForBlocks = false,
  counterpartyKeyOverrides?: Record<string, string>,
): Promise<boolean> {
  let counterpartyPub;
  try {
    counterpartyPub = rawHexToPublicKey(earn.counterparty_pubkey);
  } catch {
    return false;
  }

  // Mine EarnEvents (task_id starts with "github:") use a different trust model:
  // the miner signs the event with their own key, and the counterparty
  // (cosigner) signs only the task payload — there is no SpendEvent cross-ref.
  if (earn.task_id.startsWith("github:")) {
    // Reject self-cosigned earns (the offline "self-mint fallback" pattern).
    // A real mine claim is always cosigned by an independent peer.
    if (earn.counterparty_pubkey === ownerPubkeyHex) return false;

    let ownerPub;
    try {
      ownerPub = rawHexToPublicKey(ownerPubkeyHex);
    } catch {
      return false;
    }
    // earn.signature must be signed by the miner (log owner).
    const earnSigOk = verifyEd25519(
      canonicalStringify(eventWithoutSignature(earn)),
      earn.signature,
      ownerPub,
    );
    if (!earnSigOk) return false;
    // counterparty_task_signature must be signed by the cosigner over the task payload.
    const taskPayload = canonicalStringify({
      task_id: earn.task_id,
      amount: earn.amount,
      claimant_pubkey: ownerPubkeyHex,
      action: "earn",
    });
    if (!verifyEd25519(taskPayload, earn.counterparty_task_signature, counterpartyPub)) {
      return false;
    }
    return true;
  }

  const earnSigOk = verifyEd25519(
    canonicalStringify(eventWithoutSignature(earn)),
    earn.signature,
    counterpartyPub,
  );
  if (!earnSigOk) return false;

  // Identity binding: when the network has an admin, the counterparty must
  // have at least one valid admin MintEvent. This closes the trivial-forgery
  // hole where an attacker generates a throwaway identity X and self-signs
  // spends in a self-controlled core to credit themselves arbitrary earns.
  // Without an admin mint, X is not a real participant and any cross-ref
  // originating from X's core is rejected.
  //
  // Bounds (rather than eliminates) fake-counterparty fraud to
  // (signup_amount × number_of_admin-blessed identities the attacker
  // controls). The admin watcher rate-limits via GitHub signup verification.
  //
  // When ADMIN_PUBKEY is unset (test/dev only — production builds always
  // have it set in shared/constants.ts), this binding cannot be enforced;
  // fall back to the cross-ref-only check.
  //
  // Memoized via coreCache so a log with N earns from the same counterparty
  // doesn't rescan the admin core N times.
  // Admin is exempt: it never mints to itself so replayAdminMints(ADMIN_PUBKEY)=0.
  // verifiedMintedPubkeys disambiguates three modes for cross-side consistency:
  //   - Set: strict mode using a pre-verified set (mirrors acceptor's view)
  //   - null: explicit no-enforce (acceptor signaled they don't gate on admin mints,
  //           e.g. their ADMIN_PUBKEY is unset — we must match to compute the same balance)
  //   - undefined: legacy fallback to replayAdminMints against the local admin core
  if (verifiedMintedPubkeys === null) {
    // skip admin mint check entirely
  } else if (ADMIN_PUBKEY && earn.counterparty_pubkey !== ADMIN_PUBKEY) {
    if (verifiedMintedPubkeys) {
      if (!verifiedMintedPubkeys.has(earn.counterparty_pubkey)) return false;
    } else {
      const mintCacheKey = `__mints__:${earn.counterparty_pubkey}`;
      let cpMints = coreCache.get(mintCacheKey) as number | undefined;
      if (cpMints === undefined) {
        cpMints = await replayAdminMints(earn.counterparty_pubkey);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        coreCache.set(mintCacheKey, cpMints as any);
      }
      if (cpMints <= 0) return false;
    }
  }

  // Cross-ref: find a matching signed SpendEvent on the counterparty's log.
  //
  // The counterparty lives on another machine, so their Hypercore key is not
  // derivable from their pubkey — `getUserCore(counterparty)` on our side
  // just creates an empty local stub. Peer messages (peer:info /
  // task:announce) carry the real hex key; we persist it in peer_keys.ts and
  // open the replicated core here. Fall back to the name-based lookup when
  // we have no mapping yet (fresh peer, or unit-test scenarios where both
  // logs share a mocked store).
  let cpCore = coreCache.get(earn.counterparty_pubkey);
  if (!cpCore) {
    try {
      // Caller-provided override takes precedence over the local peer_keys cache.
      // The acceptor (who signed this earn's counterpart spend) ships their own
      // pubkey -> ledger_core_key mapping in `task:claim` so the requester opens
      // the same Hypercore the acceptor used at earn time, even if the requester's
      // local cache is stale (peer rotated their core).
      const mappedKey = counterpartyKeyOverrides?.[earn.counterparty_pubkey]
        ?? await getPeerLedgerKey(earn.counterparty_pubkey);
      if (mappedKey) {
        const store = await getCorestore();
        cpCore = store.get(Buffer.from(mappedKey, "hex"), { valueEncoding: "utf-8" });
        await cpCore.ready();
        // Sync merkle tree. When waitForBlocks=true (active swarm context like task
        // settlement) wait for full block download with no timeout — checkpoint
        // existence will keep this fast in steady state. With waitForBlocks=false
        // (e.g. `ash status`) keep the original short timeout so balance reads
        // don't hang when the swarm isn't joined.
        const updateTimeoutMs = waitForBlocks ? 30000 : 2000;
        await withTimeout(
          Promise.resolve(cpCore.update?.()).catch(() => undefined),
          updateTimeoutMs,
        );
        if (cpCore.length > 0) {
          try {
            const dl = cpCore.download({ start: 0, end: cpCore.length });
            if (waitForBlocks) {
              await dl.done();
            } else {
              await withTimeout(dl.done(), 3000);
            }
            dl.destroy?.();
          } catch { /* non-fatal */ }
        }
      } else {
        cpCore = await getUserCore(earn.counterparty_pubkey);
      }
      coreCache.set(earn.counterparty_pubkey, cpCore);
    } catch {
      return false;
    }
  }
  const cpLen: number = cpCore.length ?? 0;
  if (cpLen === 0) return false;
  for (let j = 0; j < cpLen; j++) {
    try {
      // `wait: false` for status-style reads (no swarm); `wait: true` for
      // active swarm reads where we can pull missing blocks on demand.
      const raw = await cpCore.get(j, { wait: waitForBlocks }) as string | null;
      if (raw == null) continue;
      const ev = JSON.parse(raw) as Event;
      if (
        ev.type === "spend" &&
        ev.task_id === earn.task_id &&
        ev.amount >= earn.amount &&
        ev.counterparty_pubkey === ownerPubkeyHex
      ) {
        const sigOk = verifyEd25519(
          canonicalStringify(eventWithoutSignature(ev)),
          ev.signature,
          counterpartyPub,
        );
        if (sigOk) return true;
      }
    } catch { /* skip */ }
  }
  return false;
}

/**
 * Reads the admin's Hypercore and sums all valid MintEvents
 * targeting the given recipient pubkey.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function openAdminCore(adminCoreKeyOverride?: string): Promise<any | null> {
  if (!ADMIN_PUBKEY) return null;
  const key = adminCoreKeyOverride || ADMIN_LEDGER_KEY;
  if (key) {
    // Open by actual Hypercore key for cross-machine replication.
    const store = await getCorestore();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const core: any = store.get(Buffer.from(key, "hex"), { valueEncoding: "utf-8" });
    await core.ready();
    return core;
  }
  // Fallback: local name-based core (admin on same machine).
  return getUserCore(ADMIN_PUBKEY);
}

async function replayAdminMints(recipientPubkey: string, recipientCoreKeyHex?: string, adminCoreKeyOverride?: string): Promise<number> {
  if (!ADMIN_PUBKEY) return 0;
  try {
    const adminCore = await openAdminCore(adminCoreKeyOverride);
    if (!adminCore) return 0;
    // Pull latest blocks from any connected peer. Allow up to 8 s on cold
    // starts (DHT connection + first replication round-trip); cached after.
    await withTimeout(adminCore.update?.().catch(() => undefined), 8000);
    if (adminCore.length > 0) {
      try {
        const dl = adminCore.download({ start: 0, end: adminCore.length });
        await withTimeout(dl.done(), 5000);
        dl.destroy?.();
      } catch { /* non-fatal */ }
    }
    if (adminCore.length === 0) return 0;
    const adminPubKey = rawHexToPublicKey(ADMIN_PUBKEY);
    let total = 0;
    // Invariant: at most one `reason: "signup"` mint per recipient is credited.
    // Protects against duplicate mints from a buggy watcher or manual retry.
    let signupCounted = false;
    for (let i = 0; i < adminCore.length; i++) {
      try {
        const raw = await adminCore.get(i, { wait: false }) as string | null;
        if (raw === null) continue;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const event = JSON.parse(raw) as any;
        if (
          event.type !== "mint" ||
          event.recipient_pubkey !== recipientPubkey ||
          event.signer_pubkey !== ADMIN_PUBKEY
        ) continue;
        const valid = verifyEd25519(
          canonicalStringify(eventWithoutSignature(event)),
          event.signature,
          adminPubKey,
        );
        if (!valid) continue;
        // Core binding: if the mint names a specific core, reject it when read from a different core.
        // Mints without recipient_core_key (pre-binding) are accepted on any core for backward compat.
        if (event.recipient_core_key && recipientCoreKeyHex && event.recipient_core_key !== recipientCoreKeyHex) continue;
        if (event.reason === "signup") {
          if (signupCounted) continue;
          signupCounted = true;
        }
        total += event.amount;
      } catch { /* skip malformed */ }
    }
    return total;
  } catch {
    return 0;
  }
}

/**
 * Reads the latest verified checkpoint block from a core (O(1) in the common case).
 * Scans backwards from the tail; skips blocks that fail signature or identity checks.
 *
 * Security invariants enforced per block:
 *   1. owner_pubkey === ownerPubkeyHex — prevents cross-core replay where an attacker
 *      copies another user's checkpoint into their own core to claim a higher balance.
 *   2. Owner Ed25519 signature over checkpointPayload(event) — prevents tampering with
 *      the balance field after the checkpoint was co-signed.
 *   3. Counterparty cosignature over the same payload — prevents a user from generating
 *      a self-cosigned checkpoint with a disposable key.
 *   4. Counterparty must have at least one admin MintEvent — closes the attack where an
 *      attacker controls a throwaway identity Y, signs a fake inflated checkpoint with Y,
 *      and presents it as a legitimate counterparty cosignature.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function getLatestCheckpoint(core: any, ownerPubkeyHex: string, waitForBlocks = false): Promise<SpendCheckpointEvent | EarnCheckpointEvent | null> {
  let ownerPubKey: ReturnType<typeof rawHexToPublicKey> | null = null;
  try {
    ownerPubKey = rawHexToPublicKey(ownerPubkeyHex);
  } catch {
    return null;
  }

  const len: number = core.length ?? 0;
  let mintCache: Map<string, number> | undefined;
  for (let i = len - 1; i >= 0; i--) {
    try {
      // wait:false silently skips blocks that haven't replicated yet, which
      // makes us fall back to an older checkpoint and compute a stale balance —
      // the recurring "earn-invalid" race in pure A↔B settlements traced back
      // to exactly this. wait:true forces the block to download (caller is
      // responsible for ensuring the swarm is alive when waitForBlocks=true).
      const raw = await core.get(i, { wait: waitForBlocks }) as string | null;
      if (raw == null) continue;
      const ev = JSON.parse(raw) as Event;
      if (ev.type !== "spend_checkpoint" && ev.type !== "earn_checkpoint") continue;

      const checkpoint = ev as SpendCheckpointEvent | EarnCheckpointEvent;

      // Reject non-finite or non-integer numeric fields — NaN/Infinity would
      // propagate through balance comparisons and silently break downstream gates
      // (e.g. `requesterBalance < expectedCost` is always false when balance is NaN).
      if (!Number.isFinite(checkpoint.balance) || !Number.isInteger(checkpoint.balance)) continue;
      if (!Number.isFinite(checkpoint.amount) || !Number.isInteger(checkpoint.amount) || checkpoint.amount < 0) continue;

      // (0) Position binding: nonce must equal the block index. Without this an attacker
      //     could append a legitimately-cosigned old checkpoint (nonce=5, balance=100) at
      //     a later index (e.g., 8) to roll their balance back after spending.
      if (checkpoint.nonce !== i) continue;

      // (1) Owner binding: reject checkpoints belonging to a different identity.
      if (checkpoint.owner_pubkey !== ownerPubkeyHex) continue;

      // (2) Verify owner signature over canonical payload (both sig fields stripped).
      const payload = canonicalStringify(checkpointPayload(checkpoint));
      if (!verifyEd25519(payload, checkpoint.signature, ownerPubKey)) continue;

      // (3) Verify counterparty cosignature over the same payload.
      let counterpartyPubKey: ReturnType<typeof rawHexToPublicKey>;
      try {
        counterpartyPubKey = rawHexToPublicKey(checkpoint.counterparty_pubkey);
      } catch {
        continue;
      }
      if (!verifyEd25519(payload, checkpoint.sig_counterparty, counterpartyPubKey)) continue;

      // (4) Identity binding: counterparty must be admin-minted (Sybil filter).
      //     Cache per-pubkey to avoid O(n × admin_log_size) when scanning many blocks.
      //
      //     NOTE (not a bug): this only blocks accounts that have never been minted at all.
      //     Two colluding admin-minted users could theoretically self-cosign fake checkpoints,
      //     but that requires admin to have minted both identities. The bilateral cosig (3)
      //     plus nonce position binding (0) are the primary tamper-proof anchors; this check
      //     is a supplementary Sybil filter.
      //
      //     Admin itself is exempt: admin never mints credits to its own pubkey, so
      //     replayAdminMints(ADMIN_PUBKEY) returns 0 and the check would wrongly reject
      //     checkpoints where admin is a legitimate counterparty.
      if (ADMIN_PUBKEY && checkpoint.counterparty_pubkey !== ADMIN_PUBKEY) {
        if (mintCache === undefined) mintCache = new Map<string, number>();
        let cpMints = mintCache.get(checkpoint.counterparty_pubkey);
        if (cpMints === undefined) {
          cpMints = await replayAdminMints(checkpoint.counterparty_pubkey);
          mintCache.set(checkpoint.counterparty_pubkey, cpMints);
        }
        if (cpMints <= 0) continue;
      }

      return checkpoint;
    } catch { /* skip malformed */ }
  }
  return null;
}

/** Returns the balance for the given owner by replaying their local Hypercore.
 *  Pass `waitForBlocks=true` when called from an active-swarm context (e.g. task
 *  settlement) so cross-ref reads can pull missing counterparty blocks on demand —
 *  required for cross-side balance determinism. Status-style callers leave it false. */
export async function getLocalBalance(ownerPubkeyHex: string, waitForBlocks = false): Promise<number> {
  const core = await getUserCore(ownerPubkeyHex);
  const checkpoint = await getLatestCheckpoint(core, ownerPubkeyHex, waitForBlocks);
  if (checkpoint !== null) {
    return replayBalance(core, ownerPubkeyHex, checkpoint.balance, checkpoint.nonce + 1, undefined, waitForBlocks);
  }
  const coreKeyHex = (core.key as Buffer).toString("hex");
  const mints = await replayAdminMints(ownerPubkeyHex, coreKeyHex);
  return replayBalance(core, ownerPubkeyHex, mints, 0, undefined, waitForBlocks);
}

/**
 * Opens a remote Hypercore by key, waits up to `timeoutMs` for replication,
 * and returns the replayed balance (earn/spend + admin mints).
 *
 * The timeout is per-call; cold cores often take 5-8s to settle their
 * first block over the DHT, so the default is generous. Callers that
 * cannot afford to block (e.g. interactive `ash status`) should pass a
 * shorter window.
 */
export async function getRemoteBalance(
  coreKeyHex: string,
  recipientPubkey: string,
  timeoutMs = 8000,
  adminCoreKeyOverride?: string,
  adminMintsOverride?: unknown[],
  counterpartyMintsOverride?: unknown[] | null,
  counterpartyKeyOverrides?: Record<string, string>,
): Promise<{ balance: number; coreLength: number }> {
  const store = await getCorestore();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let core: any = store.get(
    Buffer.from(coreKeyHex, "hex"),
    { valueEncoding: "utf-8" },
  );
  await core.ready();

  const updates: Promise<void>[] = [core.update().catch(() => undefined)];
  if (ADMIN_PUBKEY) {
    updates.push(
      openAdminCore(adminCoreKeyOverride)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .then((ac: any) => ac?.update())
        .catch(() => {}),
    );
  }

  await withTimeout(Promise.all(updates), timeoutMs);

  // Fallback: if the key-based open returned no blocks (peer not yet
  // connected on LEDGER_TOPIC), try the locally-registered name-based core
  // for this pubkey. This handles offline tests and cold-start races where
  // the remote peer's corestore is accessible via a pre-seeded local copy.
  if ((core.length ?? 0) === 0) {
    try {
      const localCore = await getUserCore(recipientPubkey);
      if ((localCore.length ?? 0) > 0) {
        core = localCore;
      }
    } catch { /* ignore — stick with the key-based core */ }
  }

  // Capture length after replication so callers can validate incoming nonces.
  const coreLength: number = core.length ?? 0;

  // Pre-fetch the full block range so getLatestCheckpoint / replayBalance below
  // see the latest checkpoint instead of falling back to an older one when the
  // most recent block hasn't replicated yet. Mirrors the cross-ref download
  // pattern. This is the fix for the intermittent "earn-invalid" we hit on the
  // settle path: previously `getLatestCheckpoint` did `core.get(i, {wait:false})`,
  // silently skipped a not-yet-replicated tip block, and used a stale balance.
  if (coreLength > 0) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const dl = (core as any).download?.({ start: 0, end: coreLength });
      if (dl) {
        await withTimeout(dl.done?.() ?? Promise.resolve(), timeoutMs);
        dl.destroy?.();
      }
    } catch { /* non-fatal — checkpoint scan below will still try wait:true */ }
  }

  // counterpartyMintsOverride decides how `verifyEarnCrossRef` gates each earn:
  //   - array: strict mode — build verified set, only listed pubkeys pass
  //   - null:  no-enforce — acceptor doesn't gate on admin mints (e.g. their
  //            ADMIN_PUBKEY is unset); requester must match to compute the same balance
  //   - undefined: legacy fallback to local admin core
  const verifiedCounterpartySet = counterpartyMintsOverride === null
    ? null
    : counterpartyMintsOverride !== undefined
      ? buildVerifiedMintedPubkeySet(counterpartyMintsOverride)
      : undefined;

  // Fast-path: checkpoint balance + post-checkpoint deltas (mirrors getLocalBalance logic).
  // Both paths must be byte-identical so bilateral `prev ± amount === proposed.balance`
  // checks are sound regardless of which side reads local vs remote.
  const checkpoint = await getLatestCheckpoint(core, recipientPubkey, true);
  if (checkpoint !== null) {
    const balance = await replayBalance(core, recipientPubkey, checkpoint.balance, checkpoint.nonce + 1, verifiedCounterpartySet, true, counterpartyKeyOverrides);
    return { balance, coreLength };
  }
  // Fallback: full replay for pre-checkpoint cores or peers that never transacted.
  // When the caller provides pre-fetched mint events (cross-machine case where the
  // admin core cannot be replicated), verify their signatures locally instead of
  // reading the local admin core (which would be empty on a remote requester machine).
  const mints = adminMintsOverride !== undefined
    ? sumVerifiedAdminMints(adminMintsOverride, recipientPubkey, coreKeyHex)
    : await replayAdminMints(recipientPubkey, coreKeyHex, adminCoreKeyOverride);
  return { balance: await replayBalance(core, recipientPubkey, mints, 0, verifiedCounterpartySet, true, counterpartyKeyOverrides), coreLength };
}

/**
 * Verifies a list of admin mint events and returns the set of recipient pubkeys
 * that have at least one valid mint. Mirrors `sumVerifiedAdminMints` checks but
 * tracks identity rather than amounts. Used by `getRemoteBalance` so cross-side
 * earn cross-ref checks can short-circuit `replayAdminMints` calls into the
 * local admin core (which differs across machines).
 */
export function buildVerifiedMintedPubkeySet(mints: unknown[]): Set<string> {
  const out = new Set<string>();
  if (!ADMIN_PUBKEY) return out;
  let adminPubKey: ReturnType<typeof rawHexToPublicKey>;
  try {
    adminPubKey = rawHexToPublicKey(ADMIN_PUBKEY);
  } catch {
    return out;
  }
  for (const mintRaw of mints) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const event = mintRaw as any;
      if (event.type !== "mint" || event.signer_pubkey !== ADMIN_PUBKEY) continue;
      if (typeof event.recipient_pubkey !== "string") continue;
      if (typeof event.signature !== "string" || event.signature.length === 0) continue;
      if (typeof event.amount !== "number" || !Number.isFinite(event.amount) || event.amount <= 0) continue;
      const valid = verifyEd25519(
        canonicalStringify(eventWithoutSignature(event)),
        event.signature,
        adminPubKey,
      );
      if (!valid) continue;
      out.add(event.recipient_pubkey);
    } catch { /* skip */ }
  }
  return out;
}

/** Returns all raw events from the owner's own Hypercore (earn/spend). */
export async function getEvents(ownerPubkeyHex: string): Promise<Event[]> {
  const core = await getUserCore(ownerPubkeyHex);
  const events: Event[] = [];
  for (let i = 0; i < core.length; i++) {
    try {
      const raw = await core.get(i) as string;
      events.push(JSON.parse(raw) as Event);
    } catch { /* skip malformed */ }
  }
  return events;
}

/**
 * Verifies and sums a list of admin mint events provided by a remote peer.
 * All signature and binding checks mirror replayAdminMints so the two paths
 * produce identical results — use this when the admin core cannot be replicated
 * cross-machine (i.e. ADMIN_LEDGER_KEY is unset and the peer runs a different
 * corestore).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function sumVerifiedAdminMints(mints: unknown[], recipientPubkey: string, recipientCoreKeyHex?: string): number {
  if (!ADMIN_PUBKEY) return 0;
  let adminPubKey: ReturnType<typeof rawHexToPublicKey>;
  try {
    adminPubKey = rawHexToPublicKey(ADMIN_PUBKEY);
  } catch {
    return 0;
  }
  let total = 0;
  let signupCounted = false;
  for (const mintRaw of mints) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const event = mintRaw as any;
      if (
        event.type !== "mint" ||
        event.recipient_pubkey !== recipientPubkey ||
        event.signer_pubkey !== ADMIN_PUBKEY
      ) continue;
      if (typeof event.signature !== "string" || event.signature.length === 0) continue;
      if (typeof event.amount !== "number" || !Number.isFinite(event.amount) || event.amount <= 0) continue;
      const valid = verifyEd25519(
        canonicalStringify(eventWithoutSignature(event)),
        event.signature,
        adminPubKey,
      );
      if (!valid) continue;
      if (event.recipient_core_key && recipientCoreKeyHex && event.recipient_core_key !== recipientCoreKeyHex) continue;
      if (event.reason === "signup") {
        if (signupCounted) continue;
        signupCounted = true;
      }
      total += event.amount;
    } catch { /* skip malformed */ }
  }
  return total;
}

/** Returns all valid MintEvents from the admin core targeting the given recipient. */
export async function getAdminMintsFor(recipientPubkey: string): Promise<Event[]> {
  if (!ADMIN_PUBKEY) return [];
  try {
    const adminCore = await openAdminCore();
    if (!adminCore) return [];
    await withTimeout(adminCore.update?.().catch(() => undefined), 8000);
    if (adminCore.length > 0) {
      try {
        const dl = adminCore.download({ start: 0, end: adminCore.length });
        await withTimeout(dl.done(), 5000);
        dl.destroy?.();
      } catch { /* non-fatal */ }
    }
    if (adminCore.length === 0) return [];
    const adminPubKey = rawHexToPublicKey(ADMIN_PUBKEY);
    const mints: Event[] = [];
    for (let i = 0; i < adminCore.length; i++) {
      try {
        const raw = await adminCore.get(i, { wait: false }) as string | null;
        if (raw === null) continue;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const event = JSON.parse(raw) as any;
        if (event.type === "mint" && event.recipient_pubkey === recipientPubkey) {
          const valid = verifyEd25519(
            canonicalStringify(eventWithoutSignature(event)),
            event.signature,
            adminPubKey,
          );
          if (valid) mints.push(event as Event);
        }
      } catch { /* skip */ }
    }
    return mints;
  } catch { return []; }
}
