/**
 * Per-user event Hypercore operations.
 *
 * Each user's earn/spend events are stored in their own Hypercore inside
 * the shared Corestore at ~/.ash/corestore/. The admin's MintEvents are
 * stored in the admin's own Hypercore (named by ADMIN_PUBKEY) and read by
 * all peers during balance calculation.
 */

import { getCorestore } from "./store.ts";
import { getPeerLedgerKey } from "./peer_keys.ts";
import type { Event } from "../../shared/events.ts";
import { eventWithoutSignature } from "../../shared/events.ts";
import { ADMIN_PUBKEY, ADMIN_LEDGER_KEY } from "../../shared/constants.ts";
import { verifyEd25519, rawHexToPublicKey } from "../crypto/ed25519.ts";
import { canonicalStringify } from "../../shared/canonical.ts";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function getUserCore(ownerPubkeyHex: string): Promise<any> {
  const store = await getCorestore();
  const ns = store.namespace("ash-events");
  const core = ns.get({ name: ownerPubkeyHex, valueEncoding: "utf-8" });
  await core.ready();
  return core;
}

/** Returns the hex key of the given owner's event Hypercore. */
export async function getCoreKey(ownerPubkeyHex: string): Promise<string> {
  const core = await getUserCore(ownerPubkeyHex);
  return (core.key as Buffer).toString("hex");
}

/** Returns how many events are in the owner's Hypercore (= next nonce). */
export async function getEventCount(ownerPubkeyHex: string): Promise<number> {
  const core = await getUserCore(ownerPubkeyHex);
  return core.length as number;
}

/** Appends a signed event to the owner's Hypercore. */
export async function appendEvent(ownerPubkeyHex: string, event: Event): Promise<void> {
  const core = await getUserCore(ownerPubkeyHex);
  await core.append(JSON.stringify(event));
}

/**
 * Replays earn/spend events from a core to compute base balance.
 *
 * Replay-time invariants (forgery defense):
 *   1. SpendEvent must be signed by the log owner. Prevents third-party
 *      tampering during Hypercore replication.
 *   2. EarnEvent must be signed by `counterparty_pubkey`. Mirrors the
 *      wire-level check at serve.ts earn-cosign validation.
 *   3. EarnEvent must correspond to a matching SpendEvent on the
 *      counterparty's own log. Closes the "fake counterparty keypair"
 *      forgery: an attacker who mints a throwaway keypair Y and self-signs
 *      an earn in their own log cannot produce a matching spend in Y's
 *      core (Y is empty or never replicated), so the earn is dropped.
 *   4. Running balance stays ≥ 0. A spend that would drive balance negative
 *      is skipped rather than applied; defense-in-depth against a
 *      compromised owner signing an over-spend.
 *
 * Any event that fails these checks is treated as malformed and skipped.
 */
// `startingBalance` is the pre-applied admin-mint total for this owner;
// injecting it here lets the spend underflow guard compare against the
// real available balance instead of 0 (which would drop every spend that
// lands before the first earn — see the /status vs /history mismatch bug).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function replayBalance(core: any, ownerPubkeyHex: string, startingBalance = 0): Promise<number> {
  let balance = startingBalance;
  const len: number = core.length;
  let ownerPubKey: ReturnType<typeof rawHexToPublicKey> | null = null;
  try {
    ownerPubKey = rawHexToPublicKey(ownerPubkeyHex);
  } catch {
    return 0;
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const coreCache = new Map<string, any>();
  // Dedupe earns by task_id so a single spend cannot fund multiple earns.
  // (Each task_id is generated by the requester per task; a real workflow
  // produces exactly one earn per task_id. A duplicate earn for the same
  // task_id is either a buggy retry or a deliberate inflation attack.)
  const seenEarnTaskIds = new Set<string>();
  for (let i = 0; i < len; i++) {
    try {
      const raw = await core.get(i) as string;
      const event = JSON.parse(raw) as Event;
      if (event.type === "spend") {
        const ok = verifyEd25519(
          canonicalStringify(eventWithoutSignature(event)),
          event.signature,
          ownerPubKey,
        );
        if (!ok) continue;
        // Negative balance is allowed: it exposes fraudulent spends instead
        // of silently masking them (a skipped spend still lets the
        // counterparty claim the earn via cross-ref — so skipping creates an
        // asymmetric ledger). Live `balance > 0` checks in serve.ts still
        // gate task acceptance, so a negative owner can't keep spending.
        balance -= event.amount;
      } else if (event.type === "earn") {
        if (seenEarnTaskIds.has(event.task_id)) continue;
        if (!(await verifyEarnCrossRef(event, ownerPubkeyHex, coreCache))) continue;
        seenEarnTaskIds.add(event.task_id);
        balance += event.amount;
      }
    } catch {
      // skip malformed entries
    }
  }
  return balance;
}

/**
 * Validates a single EarnEvent observed in `ownerPubkeyHex`'s log:
 *   - signature verifies against `counterparty_pubkey`
 *   - counterparty's log contains a matching SpendEvent (same task_id,
 *     same amount ≥ earn.amount when fees apply in future, counterparty ===
 *     owner, and signed by counterparty)
 *
 * Returns true if the earn should be credited.
 */
async function verifyEarnCrossRef(
  earn: Extract<Event, { type: "earn" }>,
  ownerPubkeyHex: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  coreCache: Map<string, any>,
): Promise<boolean> {
  let counterpartyPub;
  try {
    counterpartyPub = rawHexToPublicKey(earn.counterparty_pubkey);
  } catch {
    return false;
  }

  // Mine EarnEvents (task_id starts with "github:") use a different trust model:
  // the miner signs the event with their own key, and the counterparty
  // (cosigner) signs only the task payload — there is no SpendEvent cross-ref.
  if (earn.task_id.startsWith("github:")) {
    // Reject self-cosigned earns (the offline "self-mint fallback" pattern).
    // A real mine claim is always cosigned by an independent peer.
    if (earn.counterparty_pubkey === ownerPubkeyHex) return false;

    let ownerPub;
    try {
      ownerPub = rawHexToPublicKey(ownerPubkeyHex);
    } catch {
      return false;
    }
    // earn.signature must be signed by the miner (log owner).
    const earnSigOk = verifyEd25519(
      canonicalStringify(eventWithoutSignature(earn)),
      earn.signature,
      ownerPub,
    );
    if (!earnSigOk) return false;
    // counterparty_task_signature must be signed by the cosigner over the task payload.
    const taskPayload = canonicalStringify({
      task_id: earn.task_id,
      amount: earn.amount,
      claimant_pubkey: ownerPubkeyHex,
      action: "earn",
    });
    if (!verifyEd25519(taskPayload, earn.counterparty_task_signature, counterpartyPub)) {
      return false;
    }
    // Identity binding: the cosigner must be admin-minted (real participant).
    // Same rationale as the spend-cross-ref path below.
    if (ADMIN_PUBKEY) {
      const mintCacheKey = `__mints__:${earn.counterparty_pubkey}`;
      let cpMints = coreCache.get(mintCacheKey) as number | undefined;
      if (cpMints === undefined) {
        cpMints = await replayAdminMints(earn.counterparty_pubkey);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        coreCache.set(mintCacheKey, cpMints as any);
      }
      if (cpMints <= 0) return false;
    }
    return true;
  }

  const earnSigOk = verifyEd25519(
    canonicalStringify(eventWithoutSignature(earn)),
    earn.signature,
    counterpartyPub,
  );
  if (!earnSigOk) return false;

  // Identity binding: when the network has an admin, the counterparty must
  // have at least one valid admin MintEvent. This closes the trivial-forgery
  // hole where an attacker generates a throwaway identity X and self-signs
  // spends in a self-controlled core to credit themselves arbitrary earns.
  // Without an admin mint, X is not a real participant and any cross-ref
  // originating from X's core is rejected.
  //
  // Bounds (rather than eliminates) fake-counterparty fraud to
  // (signup_amount × number_of_admin-blessed identities the attacker
  // controls). The admin watcher rate-limits via GitHub signup verification.
  //
  // When ADMIN_PUBKEY is unset (test/dev only — production builds always
  // have it set in shared/constants.ts), this binding cannot be enforced;
  // fall back to the cross-ref-only check.
  //
  // Memoized via coreCache so a log with N earns from the same counterparty
  // doesn't rescan the admin core N times.
  if (ADMIN_PUBKEY) {
    const mintCacheKey = `__mints__:${earn.counterparty_pubkey}`;
    let cpMints = coreCache.get(mintCacheKey) as number | undefined;
    if (cpMints === undefined) {
      cpMints = await replayAdminMints(earn.counterparty_pubkey);
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      coreCache.set(mintCacheKey, cpMints as any);
    }
    if (cpMints <= 0) return false;
  }

  // Cross-ref: find a matching signed SpendEvent on the counterparty's log.
  //
  // The counterparty lives on another machine, so their Hypercore key is not
  // derivable from their pubkey — `getUserCore(counterparty)` on our side
  // just creates an empty local stub. Peer messages (peer:info /
  // task:announce) carry the real hex key; we persist it in peer_keys.ts and
  // open the replicated core here. Fall back to the name-based lookup when
  // we have no mapping yet (fresh peer, or unit-test scenarios where both
  // logs share a mocked store).
  let cpCore = coreCache.get(earn.counterparty_pubkey);
  if (!cpCore) {
    try {
      const mappedKey = await getPeerLedgerKey(earn.counterparty_pubkey);
      if (mappedKey) {
        const store = await getCorestore();
        cpCore = store.get(Buffer.from(mappedKey, "hex"), { valueEncoding: "utf-8" });
        await cpCore.ready();
        // Give replication a brief window to catch up before we read.
        await Promise.race([
          Promise.resolve(cpCore.update?.()).catch(() => undefined),
          new Promise<void>((r) => setTimeout(r, 2000)),
        ]);
      } else {
        cpCore = await getUserCore(earn.counterparty_pubkey);
      }
      coreCache.set(earn.counterparty_pubkey, cpCore);
    } catch {
      return false;
    }
  }
  const cpLen: number = cpCore.length ?? 0;
  if (cpLen === 0) return false;
  for (let j = 0; j < cpLen; j++) {
    try {
      // `wait: false` returns null for blocks we don't have locally instead
      // of blocking forever on replication. Balance replay runs without a
      // swarm (e.g. `ash status`), so a remote block is never going to
      // arrive here — skip it rather than hang.
      const raw = await cpCore.get(j, { wait: false }) as string | null;
      if (raw == null) continue;
      const ev = JSON.parse(raw) as Event;
      if (
        ev.type === "spend" &&
        ev.task_id === earn.task_id &&
        ev.amount >= earn.amount &&
        ev.counterparty_pubkey === ownerPubkeyHex
      ) {
        const sigOk = verifyEd25519(
          canonicalStringify(eventWithoutSignature(ev)),
          ev.signature,
          counterpartyPub,
        );
        if (sigOk) return true;
      }
    } catch { /* skip */ }
  }
  return false;
}

/**
 * Reads the admin's Hypercore and sums all valid MintEvents
 * targeting the given recipient pubkey.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function openAdminCore(): Promise<any | null> {
  if (!ADMIN_PUBKEY) return null;
  if (ADMIN_LEDGER_KEY) {
    // Open by actual Hypercore key for cross-machine replication.
    const store = await getCorestore();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const core: any = store.get(Buffer.from(ADMIN_LEDGER_KEY, "hex"), { valueEncoding: "utf-8" });
    await core.ready();
    return core;
  }
  // Fallback: local name-based core (admin on same machine).
  return getUserCore(ADMIN_PUBKEY);
}

async function replayAdminMints(recipientPubkey: string): Promise<number> {
  if (!ADMIN_PUBKEY) return 0;
  try {
    const adminCore = await openAdminCore();
    if (!adminCore || adminCore.length === 0) return 0;
    const adminPubKey = rawHexToPublicKey(ADMIN_PUBKEY);
    let total = 0;
    // Invariant: at most one `reason: "signup"` mint per recipient is credited.
    // Protects against duplicate mints from a buggy watcher or manual retry.
    let signupCounted = false;
    for (let i = 0; i < adminCore.length; i++) {
      try {
        const raw = await adminCore.get(i) as string;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const event = JSON.parse(raw) as any;
        if (
          event.type !== "mint" ||
          event.recipient_pubkey !== recipientPubkey ||
          event.signer_pubkey !== ADMIN_PUBKEY
        ) continue;
        const valid = verifyEd25519(
          canonicalStringify(eventWithoutSignature(event)),
          event.signature,
          adminPubKey,
        );
        if (!valid) continue;
        if (event.reason === "signup") {
          if (signupCounted) continue;
          signupCounted = true;
        }
        total += event.amount;
      } catch { /* skip malformed */ }
    }
    return total;
  } catch {
    return 0;
  }
}

/** Returns the balance for the given owner by replaying their local Hypercore. */
export async function getLocalBalance(ownerPubkeyHex: string): Promise<number> {
  const mints = await replayAdminMints(ownerPubkeyHex);
  const core = await getUserCore(ownerPubkeyHex);
  return replayBalance(core, ownerPubkeyHex, mints);
}

/**
 * Opens a remote Hypercore by key, waits up to `timeoutMs` for replication,
 * and returns the replayed balance (earn/spend + admin mints).
 *
 * The timeout is per-call; cold cores often take 5-8s to settle their
 * first block over the DHT, so the default is generous. Callers that
 * cannot afford to block (e.g. interactive `ash status`) should pass a
 * shorter window.
 */
export async function getRemoteBalance(
  coreKeyHex: string,
  recipientPubkey: string,
  timeoutMs = 8000,
): Promise<number> {
  const store = await getCorestore();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const core: any = store.get(
    Buffer.from(coreKeyHex, "hex"),
    { valueEncoding: "utf-8" },
  );
  await core.ready();

  const updates: Promise<void>[] = [core.update()];
  if (ADMIN_PUBKEY) {
    updates.push(
      openAdminCore()
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .then((ac: any) => ac?.update())
        .catch(() => {}),
    );
  }

  await Promise.race([
    Promise.all(updates),
    new Promise<void>((r) => setTimeout(r, timeoutMs)),
  ]);

  const mints = await replayAdminMints(recipientPubkey);
  return replayBalance(core, recipientPubkey, mints);
}

/** Returns all raw events from the owner's own Hypercore (earn/spend). */
export async function getEvents(ownerPubkeyHex: string): Promise<Event[]> {
  const core = await getUserCore(ownerPubkeyHex);
  const events: Event[] = [];
  for (let i = 0; i < core.length; i++) {
    try {
      const raw = await core.get(i) as string;
      events.push(JSON.parse(raw) as Event);
    } catch { /* skip malformed */ }
  }
  return events;
}

/** Returns all valid MintEvents from the admin core targeting the given recipient. */
export async function getAdminMintsFor(recipientPubkey: string): Promise<Event[]> {
  if (!ADMIN_PUBKEY) return [];
  try {
    const adminCore = await openAdminCore();
    if (adminCore.length === 0) return [];
    const adminPubKey = rawHexToPublicKey(ADMIN_PUBKEY);
    const mints: Event[] = [];
    for (let i = 0; i < adminCore.length; i++) {
      try {
        const raw = await adminCore.get(i) as string;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const event = JSON.parse(raw) as any;
        if (event.type === "mint" && event.recipient_pubkey === recipientPubkey) {
          const valid = verifyEd25519(
            canonicalStringify(eventWithoutSignature(event)),
            event.signature,
            adminPubKey,
          );
          if (valid) mints.push(event as Event);
        }
      } catch { /* skip */ }
    }
    return mints;
  } catch { return []; }
}
